name: Metrics
on:
  # Schedule hourly updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}

          template: classic
          config_timezone: Australia/Sydney
          repositories: 150
          plugin_languages: yes
          plugin_languages_ignored: javascript, html, css, php
          plugin_languages_colors: github
          plugin_lines: yes
          plugin_notable: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 10
          #
          plugin_wakatime: yes
          plugin_wakatime_url: https://wakapi.canine.tools
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graph, os, projects
          #
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_ID }}, ${{ secrets.SPOTIFY_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_mode: recent
          #
          plugin_activity: no
          plugin_habits: yes
          #
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://dev.astolfo.cafe
